Repository namhoangle236/DEV-272-Final, pull requests merged in 2025-06, with the labels that each got.

#14 move hook above retrun statement in root layout
  app/_layout.tsx
  package-lock.json
  package.json
Labels: help wanted

#16 added sprint closeout and retrospective
  retrospectives/week07-sprint-closeout.md
  retrospectives/week07-team-sprint-retrospective.png
Labels: TODO

#19 Updated readme.md file
  README.md
Labels: documentation
